export const QUESTIONS_B = [
  {"kicker":"장기 부재 계획","text":"며칠간 집을 비워야 한다면 가장 먼저 준비할 것은?","hint":"믿을 수 있는 사람이 돌봄을 도와준다고 가정합니다.","options":[{"text":"급여와 점검 일정, 비상 연락처를 한 번에 정리한다.","scores":{"strategist":3,"recorder":2,"architect":1}},{"text":"온도와 물, 탈출 방지 장치가 안정적인지 점검한다.","scores":{"architect":3,"strategist":2,"naturalist":1}},{"text":"평소 행동과 주의할 신호를 돌봄 담당자에게 알려준다.","scores":{"observer":3,"naturalist":2,"strategist":1}},{"text":"익숙한 냄새와 생활 루틴이 최대한 유지되게 한다.","scores":{"naturalist":3,"companion":2,"strategist":1}}]},
  {"kicker":"주말 루틴","text":"시간이 넉넉한 주말, 가장 하고 싶은 관리는?","hint":"하나만 고른다면 무엇인가요?","options":[{"text":"케이지 구조와 온도 동선을 천천히 재점검한다.","scores":{"architect":3,"naturalist":2,"recorder":1}},{"text":"평소보다 오래 조용히 관찰하고 행동을 메모한다.","scores":{"observer":3,"recorder":2,"naturalist":1}},{"text":"간식과 기다림으로 편안한 교감 시간을 만든다.","scores":{"companion":3,"naturalist":2,"observer":1}},{"text":"다가올 계절과 생활 변화에 필요한 준비를 정리한다.","scores":{"strategist":3,"recorder":2,"architect":1}}]},
  {"kicker":"이상 징후","text":"건강 이상이 의심될 때 내 행동에 가장 가까운 것은?","hint":"진단이 아닌 초기 대응 상황입니다.","options":[{"text":"언제부터 무엇이 달라졌는지 관찰 항목을 정리한다.","scores":{"observer":3,"recorder":2,"architect":1}},{"text":"체중·먹이·배변·온도 기록을 모아 상담할 자료를 만든다.","scores":{"recorder":3,"observer":2,"strategist":1}},{"text":"보온과 안정 공간을 확보하고 자극을 최소화한다.","scores":{"architect":3,"naturalist":2,"companion":1}},{"text":"불안해하지 않도록 조용히 곁을 지키며 전문 상담을 준비한다.","scores":{"companion":3,"observer":2,"naturalist":1}}]},
  {"kicker":"은신처 선택","text":"은신처를 새로 고를 때 가장 중요한 기준은?","hint":"디자인 외의 기준을 골라주세요.","options":[{"text":"안정적인 온도와 접근성, 청소 동선을 함께 본다.","scores":{"architect":3,"recorder":2,"observer":1}},{"text":"재질과 크기를 여러 개 준비해 개체가 고르게 한다.","scores":{"naturalist":3,"architect":2,"observer":1}},{"text":"실제로 어느 은신처를 얼마나 쓰는지 관찰한다.","scores":{"observer":3,"recorder":2,"naturalist":1}},{"text":"사람과의 교감 후 바로 쉴 수 있는 안전한 위치에 둔다.","scores":{"companion":3,"architect":2,"naturalist":1}}]},
  {"kicker":"가장 뿌듯한 순간","text":"집사로서 가장 큰 만족을 느끼는 순간은?","hint":"당신에게 가장 중요한 성취를 골라주세요.","options":[{"text":"작은 행동 변화의 원인을 알아냈을 때.","scores":{"observer":3,"recorder":2,"architect":1}},{"text":"새 환경에서 편안하게 쉬는 모습을 볼 때.","scores":{"architect":3,"naturalist":2,"companion":1}},{"text":"피그미가 먼저 다가와 신뢰를 보여줄 때.","scores":{"companion":3,"naturalist":2,"observer":1}},{"text":"미리 세운 장기 돌봄 계획이 안정적으로 이어질 때.","scores":{"strategist":3,"recorder":2,"architect":1}}]},
  {"kicker":"용품 구매","text":"새 사육 용품을 살 때 가장 먼저 보는 것은?","hint":"가격은 비슷하다고 가정합니다.","options":[{"text":"안전성과 온도·공간 구조에 미치는 영향.","scores":{"architect":3,"naturalist":2,"observer":1}},{"text":"관리 기록과 청소 루틴에 얼마나 잘 맞는지.","scores":{"recorder":3,"architect":2,"strategist":1}},{"text":"개체가 즐겁게 탐색하거나 교감에 활용할 수 있는지.","scores":{"companion":3,"naturalist":2,"observer":1}},{"text":"계절이 바뀌어도 오래 안전하게 활용할 수 있는지.","scores":{"strategist":3,"architect":2,"recorder":1}}]},
  {"kicker":"초보 집사에게","text":"처음 키우는 사람에게 한 가지만 조언한다면?","hint":"가장 먼저 알려주고 싶은 말을 골라주세요.","options":[{"text":"평소 모습을 알아야 이상도 알아챌 수 있어요.","scores":{"observer":3,"recorder":2,"companion":1}},{"text":"온도와 탈출 방지, 은신처부터 안정적으로 준비하세요.","scores":{"architect":3,"naturalist":2,"recorder":1}},{"text":"친해지려 서두르지 말고 먼저 기다려 주세요.","scores":{"companion":3,"naturalist":2,"observer":1}},{"text":"간단한 기록이라도 첫날부터 남겨두세요.","scores":{"recorder":3,"observer":2,"strategist":1}}]},
  {"kicker":"루틴이 깨진 날","text":"바빠서 평소 관리 루틴을 놓친 날에는?","hint":"다음 행동을 골라주세요.","options":[{"text":"핵심 기록만 남기고 다음 날 정상 루틴으로 돌아간다.","scores":{"recorder":3,"architect":2,"observer":1}},{"text":"먹이·물·온도·안전만 우선 확인한다.","scores":{"architect":3,"recorder":2,"naturalist":1}},{"text":"짧게라도 얼굴과 반응을 살피며 안정감을 준다.","scores":{"companion":3,"observer":2,"naturalist":1}},{"text":"개체가 스스로 쉴 수 있도록 자극을 줄이고 지켜본다.","scores":{"naturalist":3,"observer":2,"architect":1}}]}
];
